#!/usr/bin/env python3
"""
Meta-analysis Forest Plotter
Generate forest plots for meta-analysis with R/Python code.
"""

import argparse
import json


class ForestPlotGenerator:
    """Generate forest plot code for meta-analysis."""
    
    def generate_r_code(self, studies, output_file="forest_plot.pdf"):
        """Generate R code for forest plot."""
        code = f'''# Meta-analysis Forest Plot
# Generated by Meta-analysis Forest Plotter

library(meta)

# Study data
study_names <- c({', '.join([f'"{s["name"]}"' for s in studies])})
effects <- c({', '.join([str(s["effect"]) for s in studies])})
lower_ci <- c({', '.join([str(s["lower"]) for s in studies])})
upper_ci <- c({', '.join([str(s["upper"]) for s in studies])})
weights <- c({', '.join([str(s.get("weight", 1)) for s in studies])})

# Create meta-analysis object
meta_obj <- metagen(
  TE = effects,
  lower = lower_ci,
  upper = upper_ci,
  studlab = study_names,
  sm = "OR",
  fixed = TRUE,
  random = TRUE
)

# Generate forest plot
pdf("{output_file}", width=10, height=8)
forest(meta_obj,
       leftcols = c("studlab"),
       rightcols = c("effect", "ci"),
       print.I2 = TRUE,
       print.tau2 = TRUE)
dev.off()

print("Forest plot saved to: {output_file}")
'''
        return code
    
    def generate_python_code(self, studies, output_file="forest_plot.png"):
        """Generate Python code for forest plot."""
        code = f'''# Meta-analysis Forest Plot
# Generated by Meta-analysis Forest Plotter

import matplotlib.pyplot as plt
import numpy as np

# Study data
studies = {json.dumps(studies, indent=2)}

# Extract data
study_names = [s["name"] for s in studies]
effects = [s["effect"] for s in studies]
lower_ci = [s["lower"] for s in studies]
upper_ci = [s["upper"] for s in studies]

# Calculate errors
errors = [[e - l for e, l in zip(effects, lower_ci)],
          [u - e for e, u in zip(effects, upper_ci)]]

# Create plot
fig, ax = plt.subplots(figsize=(10, 6))

y_pos = np.arange(len(study_names))
ax.errorbar(effects, y_pos, xerr=errors, fmt='o', capsize=5)

# Add study names
ax.set_yticks(y_pos)
ax.set_yticklabels(study_names)

# Add vertical line at null effect
ax.axvline(x=1, color='red', linestyle='--', alpha=0.5, label='Null effect')

ax.set_xlabel('Effect Size (Odds Ratio)')
ax.set_title('Meta-analysis Forest Plot')
ax.legend()

plt.tight_layout()
plt.savefig("{output_file}", dpi=300)
print("Forest plot saved to: {output_file}")
'''
        return code


def main():
    parser = argparse.ArgumentParser(description="Meta-analysis Forest Plotter")
    parser.add_argument("--language", "-l", choices=["r", "python"], default="r",
                       help="Programming language")
    parser.add_argument("--output", "-o", help="Output code file")
    parser.add_argument("--demo", action="store_true", help="Generate demo code")
    
    args = parser.parse_args()
    
    generator = ForestPlotGenerator()
    
    # Demo studies
    studies = [
        {"name": "Study 1", "effect": 0.8, "lower": 0.6, "upper": 1.0, "weight": 25},
        {"name": "Study 2", "effect": 0.7, "lower": 0.5, "upper": 0.9, "weight": 30},
        {"name": "Study 3", "effect": 0.9, "lower": 0.7, "upper": 1.1, "weight": 20},
        {"name": "Study 4", "effect": 0.6, "lower": 0.4, "upper": 0.8, "weight": 25}
    ]
    
    if args.language == "r":
        code = generator.generate_r_code(studies)
    else:
        code = generator.generate_python_code(studies)
    
    print(code)
    
    if args.output:
        with open(args.output, 'w') as f:
            f.write(code)
        print(f"\nCode saved to: {args.output}")


if __name__ == "__main__":
    main()
